- Cartfile.resolved
- KumulosSDK.xcodeproj/project.pbxproj
- KumulosSDK.xcodeproj/xcshareddata/xcschemes/KumulosSDK iOS.xcscheme
- KumulosSDK.xcodeproj/xcshareddata/xcschemes/KumulosSDK macOS.xcscheme
- KumulosSdkObjectiveC.podspec
- Sources/Info-iOS.plist
- Sources/Info-macOS.plist
Prevent intermittent build failures by explicitly referencing dependency targets from the SDK schemes.
Also bumps AFNetworking version.
> Scheme updates

- KumulosSdkObjectiveC.podspec
- Sources/AuthedJsonHttpClient.h
- Sources/Info-iOS.plist
- Sources/Info-macOS.plist
- Sources/Kumulos+Crash.m
- Sources/Kumulos+Protected.h
- Sources/Kumulos.m
- Sources/RpcHttpClient.h
Works around an issue with Cordova plugin usage from a pod where headers can't be resolved using the system style imports. See https://issues.apache.org/jira/browse/CB-14057.
> Use quoted header import style for dependencies in CocoaPods usage

- KumulosSDK.xcodeproj/project.pbxproj
The modern build system has an issue when sharing a derived data directory
and invoked from the combined build script.
The fix separates the derived data dir for each SDK in turn.
Also makes the static library target dependencies explicit instead of implicit.
> Update script that generates the combined static library

- KumulosSdkObjectiveC.podspec
- README.md
- Sources/Info-iOS.plist
- Sources/Info-macOS.plist
- Sources/KSUserNotificationCenterDelegate.m
- Sources/Kumulos+Push.h
- Sources/Kumulos.h
- Sources/Kumulos.m
Allows customisation of presentation / handling of pushes received whilst the app is active.
> Add configurable push received in foreground handler

- KumulosSdkObjectiveC.podspec
- Sources/Info-iOS.plist
- Sources/Info-macOS.plist
- Sources/Kumulos+Stats.m
To fix issues with some CocoaPods setups that report the SDK version as app version, we have moved the version to a const in SDK sources.
> Add constant for base SDK version

- KumulosSdkObjectiveC.podspec
- README.md
- Sources/InApp/KSInAppHelper.m
- Sources/Info-iOS.plist
- Sources/Info-macOS.plist
- Sources/Kumulos+Stats.m
In order to deliver in-app messages in a more timely manner, we add additional sync behaviour as follows:
- fetch & present messages when the in-app feature initialises
- debug builds fetch & present messages on every foreground
- release builds fetch & present messages on foreground if no sync within 1 hour
In addition we serialise the sync logic so syncs cannot overlap in case multiple syncs are triggered at the same time.
-   None
Prepare:
-   [x] `Sources/Info-*.plist`
Release:
-   [ ] …
> In-app sync additions

- KumulosSdkObjectiveC.podspec
- Sources/InApp/KSInAppHelper.m
- Sources/InApp/KSInAppPresenter.m
- Sources/Info-iOS.plist
- Sources/Info-macOS.plist
- Sources/Kumulos+Stats.m
- Clear in-app push from tray prior to clearing currentMessage state
- Remove spinner constraints to fix warnings/simplify code
- Remove isActive guard in handling in-app deep link from push open
-  Connect the in-app UIWindow to the current scene if on iOS13
-   None
Prepare:
-   [x] Verify conditional compilation & functionality in iOS13 UIScene app in Xcode 11
-   [x] `Sources/Info-*.plist`
Release:
-   [ ] Run `pod trunk push` to …
> Minor in-app fixes

- KumulosSdkObjectiveC.podspec
- README.md
- Sources/Info-iOS.plist
- Sources/Info-macOS.plist
- Sources/Kumulos+Push.h
- Sources/Kumulos+Push.m
- Sources/Kumulos+Stats.m
Add Notification Service Extension to support pictures in push notifications. Implementation of the extension is added to Kumulos + Push. Users have to perform following steps to enable the functionality:
1) add Notification Service Extension to an application
2)  replace contents of `didReceiveNotificationRequest` with `[Kumulos didReceiveNotificationRequest:request withContentHandler: contentHandler];`
3) Make sure Notification Service's deployment target matches test device
Works on ios 10+, notifications expand only on devices that have 3D Touch
-   None
Prepare:
-   [x] …
> Support pictures in push notifications

- KumulosSdkObjectiveC.podspec
- README.md
- Sources/InApp/KSInAppHelper.m
- Sources/InApp/KSInAppModels.h
- Sources/InApp/KSInAppModels.m
- Sources/Info-iOS.plist
- Sources/Info-macOS.plist
- Sources/Kumulos+Stats.m
1) Support message expiry. Add an expiresAt column. After a message is saved delete (also) expired messages. Don't read expired messages.
2) copy field values when mapping MessageEntity into Message
-   None
Prepare:
-   [x] `Sources/Info-*.plist`
Release:
-   [ ] Run `pod trunk push` to publish to CocoaPods
> Message expiry

- KumulosSDK.xcodeproj/project.pbxproj
- KumulosSDK.xcodeproj/xcshareddata/xcschemes/KumulosSDK iOS.xcscheme
- KumulosSDK.xcodeproj/xcshareddata/xcschemes/KumulosSDKExtension.xcscheme
- KumulosSdkObjectiveC.podspec
- KumulosSdkObjectiveCExtension.podspec
- README.md
- Sources/Http/KSUrlEncoding.m
- Sources/Info-macOS.plist
- Sources/Kumulos+Push.h
- Sources/Kumulos+Push.m
- Sources/Kumulos+Stats.m
- Sources/KumulosSDKExtension/Info.plist
- Sources/KumulosSDKExtension/KumulosNotificationService.h
- Sources/KumulosSDKExtension/KumulosNotificationService.m
- Sources/KumulosSDKExtension/KumulosSDKExtension.h
When adding the SDK as a dependency for a notification service extension target in a CocoaPods app, the link step fails due to KSCrash consuming unavailable APIs.
This PR splits out the notification service helper code into a separate target and Podspec which allows linking as a separate framework, avoiding the notification service extension issues.
This means a consumer will integrate as follows:
```ruby
target 'YourApp' do
pod 'KumulosSdkObjectiveC'
end
target 'YourAppExtension' do
pod 'KumulosSdkObjectiveCExtension'
end
```
-  [Kumulos didReceiveNotificationRequest:withContentHandler]; helper removed from base SDK and moved to the KumulosNotificationService class in the KumulosSDKExtension target
Prepare:
-   [x] Detail any breaking changes. Breaking changes require a new major version …
> Move NotificationServiceExtension into a pod

- .github/pull_request_template.md
- KumulosSDK.xcodeproj/project.pbxproj
- KumulosSdkObjectiveC.podspec
- KumulosSdkObjectiveCExtension.podspec
- README.md
- Sources/Info-iOS.plist
- Sources/Info-macOS.plist
- Sources/KSUserNotificationCenterDelegate.m
- Sources/Kumulos+Push.h
- Sources/Kumulos+Push.m
- Sources/Kumulos+PushProtected.h
- Sources/Kumulos+Stats.m
Allow handling local notifications with your own implementation of `UNUserNotificationCenterDelegate`.
The delegate must be set as the current notification center delegate prior to initializing Kumulos. In addition, the delegate must be strongly retained (the SDK will not retain it).
Fixes #41.
-   None
Prepare:
-   [x] `Sources/Info-*.plist`
Release:
-   [ ] Run `pod trunk push` to …
> Allow handling local notifications with your own delegate

- Sources/KSUserNotificationCenterDelegate.m
- Sources/Kumulos.h
- Sources/Kumulos.m
Due to the Xamarin SDK depending on this SDK for native bindings and limitations of the JIT->AOT compilation for iOS code we are encountering runtime exceptions in Xamarin apps that make use of the pushReceivedInForegroundHandler.
In its current implementation the SDK gives the provided handler a reference back to the completionHandler method to be called from the managed code layer, this creates the runtime exception.
Related documentation: https://docs.microsoft.com/en-gb/xamarin/ios/internals/limitations#using-delegates-to-call-native-functions
- `setPushReceivedInForegroundHandler` will be called with only 1 parameter (the notification)
- `setForegroundPushPresentationOptions` on configuration, allows consumers to set the behaviour for presentation of notifications received while app …
> Config setting for foreground push presentation

- KumulosSDK.xcodeproj/project.pbxproj
- KumulosSdkObjectiveC.podspec
- KumulosSdkObjectiveCExtension.podspec
- Sources/Http/KSUrlEncoding.m
- Sources/Http/NSString+URLEncoding.h
- Sources/Http/NSString+URLEncoding.m
- Sources/InApp/KSInAppHelper.m
- Sources/Kumulos+Push.m
- Sources/Kumulos+Stats.m
1) Don't touch encoding of body. 
2) Update encoding of URLs to conform to RFC 3986
3) Encode userIdentifier in in-app message sync path
4) Sync in-app if not found when opening from push notification
5) Fix 'new data' conditional in in-app syncs
-   None
Prepare:
-   [ ] Check `pod lib lint` passes
-   [ ] All relevant build targets
-   [ ] `README.md`
Release:
-   [ ] Run `pod trunk push` to publish to CocoaPods
> Misc minor bug fixes & improvements

- KumulosSDK.xcodeproj/project.pbxproj
- KumulosSdkObjectiveC.podspec
- KumulosSdkObjectiveCExtension.podspec
- README.md
- Sources/InApp/KSInAppHelper.h
- Sources/InApp/KSInAppHelper.m
- Sources/Kumulos+Stats.m
- Sources/KumulosEvents.h
- Sources/KumulosEvents.m
- Sources/KumulosInApp.h
- Sources/KumulosInApp.m
New public function `deleteMessageFromInbox:item`. It sends `k.message.inbox.deleted` event and sets inbox columns to nil. This transforms the message into a message without inbox. Eviction/presentation rules of a message without inbox apply.
Additionally, when saving messages:
- update dismissedAt only if it is currently nil
- set inbox columns to nil if payload contains `inboxDeletedAt`
Ported from Swift https://github.com/Kumulos/KumulosSdkSwift/pull/50
-   None
Prepare: …
> Delete messages from inbox 

- KumulosSDK.xcodeproj/project.pbxproj
- KumulosSdkObjectiveC.podspec
- KumulosSdkObjectiveCExtension.podspec
- Sources/Kumulos+Stats.m
- Sources/Kumulos.h
- Sources/Shared/Http/KSHttpClient.m
- Sources/Shared/KumulosErrors.h
The Kumulos.h header was included by the HTTP client code to make use of common error enums.
This file isn't included in the extension pod's file list so it was missing.
Move the errors to a shared errors header to resolve.
-   None
Prepare:
Release:
-   [ ] Run `pod trunk push` to publish to CocoaPods
> Fix error with missing import for extension pod

- KumulosSDK.xcodeproj/project.pbxproj
- KumulosSdkObjectiveC.podspec
- KumulosSdkObjectiveCExtension.podspec
- Sources/KSSessionHelper.m
- Sources/Kumulos+Stats.m
See:
- https://github.com/Kumulos/KumulosSdkSwift/pull/62
- https://github.com/Kumulos/KumulosSdkSwift/commit/cc4b8bc8656da4612619cd39eb84e1731502c997
-   None
Prepare:
-   [ ] Install branch via Cocoapods into empty project & verify can import SDK (only needed if adding/removing files)
-   [ ] `README.md`
Release:
-   [ ] Create tag from master matching chosen …
> Port session finalisation nil time field guard from Swift

- Sources/KumulosSDKExtension/KumulosNotificationService.m
- Sources/Shared/KumulosHelper.m
1) Port of swift changes from [this pr](https://github.com/Kumulos/KumulosSdkSwift/pull/67).
2) Port of swift changes from [this pr](https://github.com/Kumulos/KumulosSdkSwift/pull/63) . This is actually not strictly necessary, as `dict[@"a"][@"b"]` works even if `a` is not set. So, just return early + consistency with swift. 
-   None
Prepare:
-   [x] Install branch via Cocoapods into empty project & verify can import SDK (only needed if adding/removing files)
- …
> Delivery receipt refactor

- KumulosSDK.xcodeproj/project.pbxproj
- KumulosSdkObjectiveC.podspec
- KumulosSdkObjectiveCExtension.podspec
- README.md
- Sources/InApp/KSInAppHelper.h
- Sources/InApp/KSInAppHelper.m
- Sources/Kumulos+Stats.m
- Sources/Kumulos.h
- Sources/Kumulos.m
- Sources/KumulosInApp.h
- Sources/KumulosInApp.m
Change API for setting onInboxUpdated handler from 
```
[KumulosInApp setInboxUpdatedHandler:^(){
//do stuff
}];
```
to
```
[config setInboxUpdatedHandler:^(){
//do stuff      
}];
```
This is a) in line with how other handlers are set b) avoids potential sequencing issues (`initialize` needed to be called before `setInboxUpdatedHandler`)
API for setting inbox updated handler has changed. 
Prepare:
-   [x] Install branch via Cocoapods into empty project & verify can import SDK (only needed if adding/removing files)
-   [x] …
> On inbox updated API change

- KumulosSDK.xcodeproj/project.pbxproj
- KumulosSdkObjectiveC.podspec
- KumulosSdkObjectiveCExtension.podspec
- README.md
- Sources/InApp/KSInAppHelper.h
- Sources/InApp/KSInAppHelper.m
- Sources/InApp/KSInAppModels.h
- Sources/InApp/KSInAppModels.m
- Sources/Kumulos+Stats.m
- Sources/Kumulos.h
- Sources/Kumulos.m
- Sources/KumulosInApp.h
- Sources/KumulosInApp.m
This reverts commit bf50bef55fea0ae6272095ad4057151d3d86e45e.
1) decided not to go forward with changing onInboxUpdated API
2) tiny tweaks: remove `inboxImagePath` property as not used, annotate imagePath as nullable
3) throw when kumulos not initialised when setting onInboxUpdatedHandler
-   None
Prepare:
-   [x] Install branch via Cocoapods into empty project & verify can import SDK (only needed if adding/removing files)
-   [x] …
> Undo API change

- KumulosSDK.xcodeproj/project.pbxproj
The only remaining consumer of the static library output is the Xamarin SDK which does not support running on simulators due to architecture conflicts. Simplify the build target script to skip the simulator / lipo / combine steps.
-   None
Not required.
> Update fat binary script

- KumulosSDK.xcodeproj/project.pbxproj
- KumulosSdkObjectiveC.podspec
- KumulosSdkObjectiveCExtension.podspec
- README.md
- Sources/Kumulos+Stats.m
- Sources/KumulosSDKExtension/KumulosNotificationService.m
Add support for UNNotificationActionIcon on notification buttons, added with iOS 15
-   None
Prepare:
-   [x] Install branch via Cocoapods into empty project & verify can import SDK (only needed if adding/removing files)
Release:
-   [ ] Run `pod trunk push` to publish to CocoaPods
Post …
> IOS15 UNNotificationActionIcon support

- KumulosSDK.xcodeproj/project.pbxproj
- KumulosSDK.xcodeproj/xcshareddata/xcschemes/KumulosSDK iOS.xcscheme
- KumulosSDK.xcodeproj/xcshareddata/xcschemes/KumulosSDK macOS.xcscheme
- KumulosSDK.xcodeproj/xcshareddata/xcschemes/KumulosSDKExtension.xcscheme
- KumulosSDK.xcodeproj/xcshareddata/xcschemes/KumulosSDKExtensionCombined.xcscheme
- KumulosSDK.xcodeproj/xcshareddata/xcschemes/KumulosSDKExtensionStatic.xcscheme
- KumulosSDK.xcodeproj/xcshareddata/xcschemes/KumulosSDKiOS.xcscheme
- KumulosSDK.xcodeproj/xcshareddata/xcschemes/KumulosSDKiOSCombined.xcscheme
- KumulosSdkObjectiveC.podspec
- KumulosSdkObjectiveCExtension.podspec
- README.md
- Sources/InApp/KSInAppPresenter.h
- Sources/InApp/KSInAppPresenter.m
- Sources/Kumulos+Analytics.h
- Sources/Kumulos+Crash.h
- Sources/Kumulos+DeepLinking.h
- Sources/Kumulos+Location.h
- Sources/Kumulos+Push.h
- Sources/Kumulos+Stats.m
- Sources/Kumulos.h
- Sources/Kumulos.m
- Sources/KumulosInApp.h
- Sources/KumulosInApp.m
- Sources/KumulosPushSubscriptionManager.h
- Sources/KumulosSDK.h
Expose in-app message data to KSInAppDeepLinkHandlerBlock:
- Port of https://github.com/Kumulos/KumulosSdkSwift/pull/80
- Update project to latest settings for Xcode 13
- Fix warnings about using double-quoted header includes in framework files
The KSInAppButtonPress class contains the original deep link button data in the deepLinkData field, and additionally offers the in-app message's ID and (optional) data field.
- `KSInAppDeepLinkHandlerBlock` now takes `KSInAppButtonPress*` as its only argument
Prepare:
-   [ ] Install branch via Cocoapods into empty project & verify can import SDK (only needed if …
> Expose in-app message data to KSInAppDeepLinkHandlerBlock
